In [11]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()
print("Keys of iris_dataset: \n{}".format(iris_dataset.keys()) + "\n")
print(iris_dataset['DESCR'][:1093] + "\n..")

Keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ===

In [18]:
print("Target Names: {}".format(iris_dataset['target_names']) + "\n")
print("Feature Names: {}".format(iris_dataset['feature_names']) + "\n")
print("Type of data: {}".format(type(iris_dataset['data'])) + "\n")
print("Shape of data: {}".format(iris_dataset['data'].shape) + "\n")

# rows in the data correspond to flowers, while columns represent the 4 measurements that were taken for each flower.
# Array contains 150 different flowers.
# the shape of the data array is the number of samples multiplied by the number of features.

Target Names: ['setosa' 'versicolor' 'virginica']

Feature Names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Type of data: <class 'numpy.ndarray'>

Shape of data: (150, 4)



In [20]:
# Feature values for the first five samples:
print("First five coloumns of data: {}".format(iris_dataset['data'][:5]) + "\n")


First five coloumns of data: [[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]



In [27]:
print("Types of Target: {}".format(type(iris_dataset['target'])) + "\n")
print("Shape of Target: {}".format(iris_dataset['target'].shape) + "\n")
print("Target: \n {}".format(iris_dataset['target']) + "\n")
print(iris_dataset['target_names'])

Types of Target: <class 'numpy.ndarray'>

Shape of Target: (150,)

Target: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]

['setosa' 'versicolor' 'virginica']


In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    iris_dataset['data'], iris_dataset['target'], random_state =0)

In [33]:
print("X_train shape: {}".format(X_train.shape))
print("y_train shape: {}".format(y_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
y_train shape: (112,)
X_test shape: (38, 4)
y_test shape: (38,)
